### ISSUE TITLE
Labeling Tool for customized Training Dataset

### ISSUE THREAD

**Issue by bsetsu** [lehommee/DPDnet-A-robust-people-detector-using-deep-learning-with-an-overhead-depth-camera#5]
Hi @lehommee 
Where can I find the labeling tool for customized training dataset?

Thanks in advance.

**Comment by dfuentes-uah** [comment]
I don't have the original labeling tool, but I prepared a .py that you can use. You only have to modify the sequence length and the paths. Click where the person is placed, and a gaussian that labels the head will appear. The name of the .py is labeling_tool.py

Best Regards,

David

![image](https://user-images.githubusercontent.com/37031058/113843273-bb1a9400-9793-11eb-8f14-6211a99780cc.png)

**Comment by bsetsu** [comment]
@lehommee Hi, Thanks for your great kind work.
I used this tool and labeled my own data, and trained but with no luck.
Same as before, nothing detected.
By the way I trained your dataset again, it also don't detect anything when I used newly trained model.

Best Regards,
Marvin

**Comment by dfuentes-uah** [comment]
Mmmm, very strange, can you send me some example images with people to try and test it in my pc?.

Regards,

David

**Comment by bsetsu** [comment]
Although the training is not working as expected yet, but the labeling tool works perfect. So, I am closing this issue.
Thanks David! @lehommee
