### ISSUE TITLE
something wrong while runing Test.py

### ISSUE THREAD

**Issue by berylyellow** [lehommee/DPDnet-A-robust-people-detector-using-deep-learning-with-an-overhead-depth-camera#7]
Hi～ Thanks for your project. But I have a question.
When I use Test.py for test,  something wrong happened.  In Test.py, there is:
[valinput, valoutput] = test(divider, canales,path,img_x,img_y)
What does it mean ?  Where is the test function?

And errors returned :
File "/usr/local/lib/python3.6/dist-packages/scipy/_lib/_testutils.py", line 39, in __call__
    raise ValueError("Doctests not supported")

Thanks for your help~

**Comment by dfuentes-uah** [comment]
Hi berylyellow, this error is very strange, this function is provided in utils.py. Can you debug to the exact point where the error occurs inside the function please?, to try and test it in my computer.

Did you manage to solve it?

Best regards, David

**Comment by dfuentes-uah** [comment]
Hi berylyellow, sorry, indeed the fault was mine, the version of the utils.py file was not updated, please try the code again now, the error should be fixed, I updated utils.py to the last version.

Best regards,

David

**Comment by berylyellow** [comment]
Thanks lehommee ~   have solved it.

**Comment by berylyellow** [comment]
Thanks lehommee ~   have solved it.
